### PR TITLE
Fix build with icu-68.1

### PR DESCRIPTION
**Pull request by Polynomial-C**
icu-68.1 removed public macro definitions for TRUE and FALSE

See icu upstream commit: https://github.com/unicode-org/icu/commit/a18df7ba2834afc2b577a1d5a7d906868ade6fa9

### CODE REVIEW

**Comment by winterz** [comment]
do we know for sure that all the world's platforms (let's say within the past 15 years) have stdbool.h?

**Comment by SoapGentoo** [comment]
`stdbool.h` is a C99 header. The problem is, ICU already exposes `stdbool.h` in other headers, hence if you're using the latest ICU, you're implicitly relying on C99 support anyways.
GCC has the `bool` macro in `stdbool.h` since GCC 3.0, which was released in 2001. I think it's safe to say that, yes, most platforms from the past 15 years have a proper `stdbool.h`.

**Comment by winterz** [comment]
see commit a3308a23912bba2db654a8c456165c31888cc897

in case some ancient compiler (like MSVC before version 2013) sees the code.
let me know what you think.
-Allen

**Comment by SoapGentoo** [comment]
MSVC always compiles in C++ mode, so doesn't need the macros for `true`/`false`

**Comment by winterz** [comment]
I tried MSVC 2010 and got this without defining false ourselves:

```
C:\projects\libical\libical\src\libical\icalrecur.c(1024) : error C2065: 'false' : undeclared identifier
C:\projects\libical\libical\src\libical\icalrecur.c(1417) : error C2065: 'false' : undeclared identifier
```
I'll leave the code as is , at least for now.
