### ISSUE TITLE
libical-3.014 does not compile with berkeley db-6.2.32

### ISSUE THREAD

**Issue by kladitt** [libical/libical#545]
libical-3.0.12 compiles without error using gcc version 10.3.1.

I got the the following errors using gcc version 10.3.1:

[ 94%] Linking C executable icalrecurtest
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `typeinfo for std::exception'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `__cxa_free_exception'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `operator delete[](void*)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `operator new(unsigned long)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `operator new[](unsigned long)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `__cxa_allocate_exception'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `__gxx_personality_v0'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `__cxa_throw'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `std::ios_base::Init::~Init()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `std::ios_base::Init::Init()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `std::exception::~exception()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `__cxa_throw_bad_array_new_length'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `std::basic_ios<char, std::char_traits<char> >::clear(std::_Ios_Iostate)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `operator delete(void*, unsigned long)'
/usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/10.3.1/../../../../lib/libdb_cxx.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
make[2]: *** [src/test/CMakeFiles/icalrecurtest.dir/build.make:102: src/test/icalrecurtest] Error 1
make[1]: *** [CMakeFiles/Makefile2:924: src/test/CMakeFiles/icalrecurtest.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by winterz** [comment]
can you show me the BDB_* values in your build/CMakeCache.txt?
ie. `grep BDB_ build/CMakeCache.txt`

**Comment by kladitt** [comment]
The problem was not of because of libdb (aka Berkely db) but much simpler,
it was solved by adding -lstdc++ to LDFLAGS .


This, I assume, was forgotten in 3.014 somewhere. 
In contrast to 3.012 which compiled fine out of the box(tar.gz)

**Comment by winterz** [comment]
can you show me your patch so I can make sure I'm fixing the right CMake code?

**Comment by kladitt** [comment]
No patch for cmake, just export LDFLAGS+=" -lstdc++" and then 
 cmake  \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=$ULL/libical \
        -DCMAKE_INSTALL_INCLUDEDIR=$ULI/libical \
        -DSHARED_ONLY=yes \
        -DICAL_BUILD_DOCS=false \
        -DICAL_GLIB_VAPI=false \
        -DGOBJECT_INTROSPECTION=true \

I don't know or care much of cmake, just that it must be bloated because it needs an update every 2 weeks since years.

**Comment by winterz** [comment]
I've been trying to reproduce this on a fresh ubuntu 22.04.  so far no luck.
I apt installed libdb-dev gobject-introspection libgirepository1.0-dev  => worked
then installed libdb++-dev => still worked

the berkeley db is version 5.3 on ubuntu 22.04, btw

not sure what else to try other then finding some distro that has db-6.2 available.

**Comment by winterz** [comment]
can you try this patch please?
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f889f985..294151c6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -263,7 +263,7 @@ if(BerkeleyDB_FOUND)
   #for compatibility to our old FindBDB
   set(BDB_FOUND True)
   set(BDB_INCLUDE_DIR ${BerkeleyDB_INCLUDE_DIRS})
-  set(BDB_LIBRARY ${BerkeleyDB_LIBRARIES})
+  set(BDB_LIBRARY ${BerkeleyDB_LIBRARY})
 endif()

 # MSVC specific definitions
```

**Comment by winterz** [comment]
no response since more than 6 months.
closing. reopen as needed.
